// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package mesos.internal.state;

public final class State {
  private State() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required bytes uuid = 2;
    /**
     * <code>required bytes uuid = 2;</code>
     */
    boolean hasUuid();
    /**
     * <code>required bytes uuid = 2;</code>
     */
    com.google.protobuf.ByteString getUuid();

    // required bytes value = 3;
    /**
     * <code>required bytes value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code mesos.internal.state.Entry}
   *
   * <pre>
   * Describes a state entry, a versioned (via a UUID) key/value pair.
   * </pre>
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage
      implements EntryOrBuilder {
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Entry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }

    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Entry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uuid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mesos.internal.state.State.internal_static_mesos_internal_state_Entry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mesos.internal.state.State.internal_static_mesos_internal_state_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mesos.internal.state.State.Entry.class, mesos.internal.state.State.Entry.Builder.class);
    }

    public static com.google.protobuf.Parser<Entry> PARSER =
        new com.google.protobuf.AbstractParser<Entry>() {
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes uuid = 2;
    public static final int UUID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString uuid_;
    /**
     * <code>required bytes uuid = 2;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes uuid = 2;</code>
     */
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }

    // required bytes value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      name_ = "";
      uuid_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mesos.internal.state.State.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mesos.internal.state.State.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mesos.internal.state.State.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mesos.internal.state.State.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mesos.internal.state.State.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mesos.internal.state.State.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mesos.internal.state.State.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mesos.internal.state.State.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mesos.internal.state.State.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mesos.internal.state.State.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mesos.internal.state.State.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mesos.internal.state.Entry}
     *
     * <pre>
     * Describes a state entry, a versioned (via a UUID) key/value pair.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mesos.internal.state.State.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mesos.internal.state.State.Entry.class, mesos.internal.state.State.Entry.Builder.class);
      }

      // Construct using mesos.internal.state.State.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Entry_descriptor;
      }

      public mesos.internal.state.State.Entry getDefaultInstanceForType() {
        return mesos.internal.state.State.Entry.getDefaultInstance();
      }

      public mesos.internal.state.State.Entry build() {
        mesos.internal.state.State.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mesos.internal.state.State.Entry buildPartial() {
        mesos.internal.state.State.Entry result = new mesos.internal.state.State.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mesos.internal.state.State.Entry) {
          return mergeFrom((mesos.internal.state.State.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mesos.internal.state.State.Entry other) {
        if (other == mesos.internal.state.State.Entry.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasUuid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mesos.internal.state.State.Entry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mesos.internal.state.State.Entry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required bytes uuid = 2;
      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes uuid = 2;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes uuid = 2;</code>
       */
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      /**
       * <code>required bytes uuid = 2;</code>
       */
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes uuid = 2;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }

      // required bytes value = 3;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mesos.internal.state.Entry)
    }

    static {
      defaultInstance = new Entry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mesos.internal.state.Entry)
  }

  public interface OperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .mesos.internal.state.Operation.Type type = 1;
    /**
     * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
     */
    mesos.internal.state.State.Operation.Type getType();

    // optional .mesos.internal.state.Operation.Snapshot snapshot = 2;
    /**
     * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
     */
    boolean hasSnapshot();
    /**
     * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
     */
    mesos.internal.state.State.Operation.Snapshot getSnapshot();
    /**
     * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
     */
    mesos.internal.state.State.Operation.SnapshotOrBuilder getSnapshotOrBuilder();

    // optional .mesos.internal.state.Operation.Expunge expunge = 3;
    /**
     * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
     */
    boolean hasExpunge();
    /**
     * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
     */
    mesos.internal.state.State.Operation.Expunge getExpunge();
    /**
     * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
     */
    mesos.internal.state.State.Operation.ExpungeOrBuilder getExpungeOrBuilder();
  }
  /**
   * Protobuf type {@code mesos.internal.state.Operation}
   *
   * <pre>
   * Describes an operation used in the log storage implementation.
   * </pre>
   */
  public static final class Operation extends
      com.google.protobuf.GeneratedMessage
      implements OperationOrBuilder {
    // Use Operation.newBuilder() to construct.
    private Operation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Operation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Operation defaultInstance;
    public static Operation getDefaultInstance() {
      return defaultInstance;
    }

    public Operation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Operation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              mesos.internal.state.State.Operation.Type value = mesos.internal.state.State.Operation.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              mesos.internal.state.State.Operation.Snapshot.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = snapshot_.toBuilder();
              }
              snapshot_ = input.readMessage(mesos.internal.state.State.Operation.Snapshot.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(snapshot_);
                snapshot_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              mesos.internal.state.State.Operation.Expunge.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = expunge_.toBuilder();
              }
              expunge_ = input.readMessage(mesos.internal.state.State.Operation.Expunge.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(expunge_);
                expunge_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mesos.internal.state.State.Operation.class, mesos.internal.state.State.Operation.Builder.class);
    }

    public static com.google.protobuf.Parser<Operation> PARSER =
        new com.google.protobuf.AbstractParser<Operation>() {
      public Operation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Operation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Operation> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code mesos.internal.state.Operation.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SNAPSHOT = 1;</code>
       */
      SNAPSHOT(0, 1),
      /**
       * <code>EXPUNGE = 2;</code>
       */
      EXPUNGE(1, 2),
      ;

      /**
       * <code>SNAPSHOT = 1;</code>
       */
      public static final int SNAPSHOT_VALUE = 1;
      /**
       * <code>EXPUNGE = 2;</code>
       */
      public static final int EXPUNGE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return SNAPSHOT;
          case 2: return EXPUNGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mesos.internal.state.State.Operation.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mesos.internal.state.Operation.Type)
    }

    public interface SnapshotOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .mesos.internal.state.Entry entry = 1;
      /**
       * <code>required .mesos.internal.state.Entry entry = 1;</code>
       */
      boolean hasEntry();
      /**
       * <code>required .mesos.internal.state.Entry entry = 1;</code>
       */
      mesos.internal.state.State.Entry getEntry();
      /**
       * <code>required .mesos.internal.state.Entry entry = 1;</code>
       */
      mesos.internal.state.State.EntryOrBuilder getEntryOrBuilder();
    }
    /**
     * Protobuf type {@code mesos.internal.state.Operation.Snapshot}
     *
     * <pre>
     * Describes a "snapshot" operation.
     * </pre>
     */
    public static final class Snapshot extends
        com.google.protobuf.GeneratedMessage
        implements SnapshotOrBuilder {
      // Use Snapshot.newBuilder() to construct.
      private Snapshot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Snapshot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Snapshot defaultInstance;
      public static Snapshot getDefaultInstance() {
        return defaultInstance;
      }

      public Snapshot getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Snapshot(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                mesos.internal.state.State.Entry.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = entry_.toBuilder();
                }
                entry_ = input.readMessage(mesos.internal.state.State.Entry.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(entry_);
                  entry_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Snapshot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mesos.internal.state.State.Operation.Snapshot.class, mesos.internal.state.State.Operation.Snapshot.Builder.class);
      }

      public static com.google.protobuf.Parser<Snapshot> PARSER =
          new com.google.protobuf.AbstractParser<Snapshot>() {
        public Snapshot parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Snapshot(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Snapshot> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .mesos.internal.state.Entry entry = 1;
      public static final int ENTRY_FIELD_NUMBER = 1;
      private mesos.internal.state.State.Entry entry_;
      /**
       * <code>required .mesos.internal.state.Entry entry = 1;</code>
       */
      public boolean hasEntry() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .mesos.internal.state.Entry entry = 1;</code>
       */
      public mesos.internal.state.State.Entry getEntry() {
        return entry_;
      }
      /**
       * <code>required .mesos.internal.state.Entry entry = 1;</code>
       */
      public mesos.internal.state.State.EntryOrBuilder getEntryOrBuilder() {
        return entry_;
      }

      private void initFields() {
        entry_ = mesos.internal.state.State.Entry.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasEntry()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getEntry().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, entry_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, entry_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static mesos.internal.state.State.Operation.Snapshot parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mesos.internal.state.State.Operation.Snapshot parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(mesos.internal.state.State.Operation.Snapshot prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code mesos.internal.state.Operation.Snapshot}
       *
       * <pre>
       * Describes a "snapshot" operation.
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements mesos.internal.state.State.Operation.SnapshotOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Snapshot_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Snapshot_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  mesos.internal.state.State.Operation.Snapshot.class, mesos.internal.state.State.Operation.Snapshot.Builder.class);
        }

        // Construct using mesos.internal.state.State.Operation.Snapshot.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getEntryFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (entryBuilder_ == null) {
            entry_ = mesos.internal.state.State.Entry.getDefaultInstance();
          } else {
            entryBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Snapshot_descriptor;
        }

        public mesos.internal.state.State.Operation.Snapshot getDefaultInstanceForType() {
          return mesos.internal.state.State.Operation.Snapshot.getDefaultInstance();
        }

        public mesos.internal.state.State.Operation.Snapshot build() {
          mesos.internal.state.State.Operation.Snapshot result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public mesos.internal.state.State.Operation.Snapshot buildPartial() {
          mesos.internal.state.State.Operation.Snapshot result = new mesos.internal.state.State.Operation.Snapshot(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (entryBuilder_ == null) {
            result.entry_ = entry_;
          } else {
            result.entry_ = entryBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof mesos.internal.state.State.Operation.Snapshot) {
            return mergeFrom((mesos.internal.state.State.Operation.Snapshot)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(mesos.internal.state.State.Operation.Snapshot other) {
          if (other == mesos.internal.state.State.Operation.Snapshot.getDefaultInstance()) return this;
          if (other.hasEntry()) {
            mergeEntry(other.getEntry());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasEntry()) {
            
            return false;
          }
          if (!getEntry().isInitialized()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          mesos.internal.state.State.Operation.Snapshot parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (mesos.internal.state.State.Operation.Snapshot) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .mesos.internal.state.Entry entry = 1;
        private mesos.internal.state.State.Entry entry_ = mesos.internal.state.State.Entry.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            mesos.internal.state.State.Entry, mesos.internal.state.State.Entry.Builder, mesos.internal.state.State.EntryOrBuilder> entryBuilder_;
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public boolean hasEntry() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public mesos.internal.state.State.Entry getEntry() {
          if (entryBuilder_ == null) {
            return entry_;
          } else {
            return entryBuilder_.getMessage();
          }
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public Builder setEntry(mesos.internal.state.State.Entry value) {
          if (entryBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            entry_ = value;
            onChanged();
          } else {
            entryBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public Builder setEntry(
            mesos.internal.state.State.Entry.Builder builderForValue) {
          if (entryBuilder_ == null) {
            entry_ = builderForValue.build();
            onChanged();
          } else {
            entryBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public Builder mergeEntry(mesos.internal.state.State.Entry value) {
          if (entryBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                entry_ != mesos.internal.state.State.Entry.getDefaultInstance()) {
              entry_ =
                mesos.internal.state.State.Entry.newBuilder(entry_).mergeFrom(value).buildPartial();
            } else {
              entry_ = value;
            }
            onChanged();
          } else {
            entryBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public Builder clearEntry() {
          if (entryBuilder_ == null) {
            entry_ = mesos.internal.state.State.Entry.getDefaultInstance();
            onChanged();
          } else {
            entryBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public mesos.internal.state.State.Entry.Builder getEntryBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getEntryFieldBuilder().getBuilder();
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        public mesos.internal.state.State.EntryOrBuilder getEntryOrBuilder() {
          if (entryBuilder_ != null) {
            return entryBuilder_.getMessageOrBuilder();
          } else {
            return entry_;
          }
        }
        /**
         * <code>required .mesos.internal.state.Entry entry = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            mesos.internal.state.State.Entry, mesos.internal.state.State.Entry.Builder, mesos.internal.state.State.EntryOrBuilder> 
            getEntryFieldBuilder() {
          if (entryBuilder_ == null) {
            entryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                mesos.internal.state.State.Entry, mesos.internal.state.State.Entry.Builder, mesos.internal.state.State.EntryOrBuilder>(
                    entry_,
                    getParentForChildren(),
                    isClean());
            entry_ = null;
          }
          return entryBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:mesos.internal.state.Operation.Snapshot)
      }

      static {
        defaultInstance = new Snapshot(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:mesos.internal.state.Operation.Snapshot)
    }

    public interface ExpungeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code mesos.internal.state.Operation.Expunge}
     *
     * <pre>
     * Describes an "expunge" operation.
     * </pre>
     */
    public static final class Expunge extends
        com.google.protobuf.GeneratedMessage
        implements ExpungeOrBuilder {
      // Use Expunge.newBuilder() to construct.
      private Expunge(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Expunge(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Expunge defaultInstance;
      public static Expunge getDefaultInstance() {
        return defaultInstance;
      }

      public Expunge getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Expunge(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Expunge_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Expunge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mesos.internal.state.State.Operation.Expunge.class, mesos.internal.state.State.Operation.Expunge.Builder.class);
      }

      public static com.google.protobuf.Parser<Expunge> PARSER =
          new com.google.protobuf.AbstractParser<Expunge>() {
        public Expunge parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Expunge(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Expunge> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        name_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static mesos.internal.state.State.Operation.Expunge parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Expunge parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static mesos.internal.state.State.Operation.Expunge parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mesos.internal.state.State.Operation.Expunge parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(mesos.internal.state.State.Operation.Expunge prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code mesos.internal.state.Operation.Expunge}
       *
       * <pre>
       * Describes an "expunge" operation.
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements mesos.internal.state.State.Operation.ExpungeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Expunge_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Expunge_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  mesos.internal.state.State.Operation.Expunge.class, mesos.internal.state.State.Operation.Expunge.Builder.class);
        }

        // Construct using mesos.internal.state.State.Operation.Expunge.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_Expunge_descriptor;
        }

        public mesos.internal.state.State.Operation.Expunge getDefaultInstanceForType() {
          return mesos.internal.state.State.Operation.Expunge.getDefaultInstance();
        }

        public mesos.internal.state.State.Operation.Expunge build() {
          mesos.internal.state.State.Operation.Expunge result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public mesos.internal.state.State.Operation.Expunge buildPartial() {
          mesos.internal.state.State.Operation.Expunge result = new mesos.internal.state.State.Operation.Expunge(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof mesos.internal.state.State.Operation.Expunge) {
            return mergeFrom((mesos.internal.state.State.Operation.Expunge)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(mesos.internal.state.State.Operation.Expunge other) {
          if (other == mesos.internal.state.State.Operation.Expunge.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          mesos.internal.state.State.Operation.Expunge parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (mesos.internal.state.State.Operation.Expunge) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:mesos.internal.state.Operation.Expunge)
      }

      static {
        defaultInstance = new Expunge(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:mesos.internal.state.Operation.Expunge)
    }

    private int bitField0_;
    // required .mesos.internal.state.Operation.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private mesos.internal.state.State.Operation.Type type_;
    /**
     * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
     */
    public mesos.internal.state.State.Operation.Type getType() {
      return type_;
    }

    // optional .mesos.internal.state.Operation.Snapshot snapshot = 2;
    public static final int SNAPSHOT_FIELD_NUMBER = 2;
    private mesos.internal.state.State.Operation.Snapshot snapshot_;
    /**
     * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
     */
    public boolean hasSnapshot() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
     */
    public mesos.internal.state.State.Operation.Snapshot getSnapshot() {
      return snapshot_;
    }
    /**
     * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
     */
    public mesos.internal.state.State.Operation.SnapshotOrBuilder getSnapshotOrBuilder() {
      return snapshot_;
    }

    // optional .mesos.internal.state.Operation.Expunge expunge = 3;
    public static final int EXPUNGE_FIELD_NUMBER = 3;
    private mesos.internal.state.State.Operation.Expunge expunge_;
    /**
     * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
     */
    public boolean hasExpunge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
     */
    public mesos.internal.state.State.Operation.Expunge getExpunge() {
      return expunge_;
    }
    /**
     * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
     */
    public mesos.internal.state.State.Operation.ExpungeOrBuilder getExpungeOrBuilder() {
      return expunge_;
    }

    private void initFields() {
      type_ = mesos.internal.state.State.Operation.Type.SNAPSHOT;
      snapshot_ = mesos.internal.state.State.Operation.Snapshot.getDefaultInstance();
      expunge_ = mesos.internal.state.State.Operation.Expunge.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasSnapshot()) {
        if (!getSnapshot().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasExpunge()) {
        if (!getExpunge().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, snapshot_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, expunge_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, snapshot_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, expunge_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mesos.internal.state.State.Operation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mesos.internal.state.State.Operation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mesos.internal.state.State.Operation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mesos.internal.state.State.Operation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mesos.internal.state.State.Operation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mesos.internal.state.State.Operation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mesos.internal.state.State.Operation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mesos.internal.state.State.Operation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mesos.internal.state.State.Operation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mesos.internal.state.State.Operation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mesos.internal.state.State.Operation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mesos.internal.state.Operation}
     *
     * <pre>
     * Describes an operation used in the log storage implementation.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mesos.internal.state.State.OperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mesos.internal.state.State.Operation.class, mesos.internal.state.State.Operation.Builder.class);
      }

      // Construct using mesos.internal.state.State.Operation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSnapshotFieldBuilder();
          getExpungeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = mesos.internal.state.State.Operation.Type.SNAPSHOT;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (snapshotBuilder_ == null) {
          snapshot_ = mesos.internal.state.State.Operation.Snapshot.getDefaultInstance();
        } else {
          snapshotBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (expungeBuilder_ == null) {
          expunge_ = mesos.internal.state.State.Operation.Expunge.getDefaultInstance();
        } else {
          expungeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mesos.internal.state.State.internal_static_mesos_internal_state_Operation_descriptor;
      }

      public mesos.internal.state.State.Operation getDefaultInstanceForType() {
        return mesos.internal.state.State.Operation.getDefaultInstance();
      }

      public mesos.internal.state.State.Operation build() {
        mesos.internal.state.State.Operation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mesos.internal.state.State.Operation buildPartial() {
        mesos.internal.state.State.Operation result = new mesos.internal.state.State.Operation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (snapshotBuilder_ == null) {
          result.snapshot_ = snapshot_;
        } else {
          result.snapshot_ = snapshotBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (expungeBuilder_ == null) {
          result.expunge_ = expunge_;
        } else {
          result.expunge_ = expungeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mesos.internal.state.State.Operation) {
          return mergeFrom((mesos.internal.state.State.Operation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mesos.internal.state.State.Operation other) {
        if (other == mesos.internal.state.State.Operation.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSnapshot()) {
          mergeSnapshot(other.getSnapshot());
        }
        if (other.hasExpunge()) {
          mergeExpunge(other.getExpunge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasSnapshot()) {
          if (!getSnapshot().isInitialized()) {
            
            return false;
          }
        }
        if (hasExpunge()) {
          if (!getExpunge().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mesos.internal.state.State.Operation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mesos.internal.state.State.Operation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .mesos.internal.state.Operation.Type type = 1;
      private mesos.internal.state.State.Operation.Type type_ = mesos.internal.state.State.Operation.Type.SNAPSHOT;
      /**
       * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
       */
      public mesos.internal.state.State.Operation.Type getType() {
        return type_;
      }
      /**
       * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
       */
      public Builder setType(mesos.internal.state.State.Operation.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .mesos.internal.state.Operation.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = mesos.internal.state.State.Operation.Type.SNAPSHOT;
        onChanged();
        return this;
      }

      // optional .mesos.internal.state.Operation.Snapshot snapshot = 2;
      private mesos.internal.state.State.Operation.Snapshot snapshot_ = mesos.internal.state.State.Operation.Snapshot.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          mesos.internal.state.State.Operation.Snapshot, mesos.internal.state.State.Operation.Snapshot.Builder, mesos.internal.state.State.Operation.SnapshotOrBuilder> snapshotBuilder_;
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public boolean hasSnapshot() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public mesos.internal.state.State.Operation.Snapshot getSnapshot() {
        if (snapshotBuilder_ == null) {
          return snapshot_;
        } else {
          return snapshotBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public Builder setSnapshot(mesos.internal.state.State.Operation.Snapshot value) {
        if (snapshotBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          snapshot_ = value;
          onChanged();
        } else {
          snapshotBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public Builder setSnapshot(
          mesos.internal.state.State.Operation.Snapshot.Builder builderForValue) {
        if (snapshotBuilder_ == null) {
          snapshot_ = builderForValue.build();
          onChanged();
        } else {
          snapshotBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public Builder mergeSnapshot(mesos.internal.state.State.Operation.Snapshot value) {
        if (snapshotBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              snapshot_ != mesos.internal.state.State.Operation.Snapshot.getDefaultInstance()) {
            snapshot_ =
              mesos.internal.state.State.Operation.Snapshot.newBuilder(snapshot_).mergeFrom(value).buildPartial();
          } else {
            snapshot_ = value;
          }
          onChanged();
        } else {
          snapshotBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public Builder clearSnapshot() {
        if (snapshotBuilder_ == null) {
          snapshot_ = mesos.internal.state.State.Operation.Snapshot.getDefaultInstance();
          onChanged();
        } else {
          snapshotBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public mesos.internal.state.State.Operation.Snapshot.Builder getSnapshotBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSnapshotFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      public mesos.internal.state.State.Operation.SnapshotOrBuilder getSnapshotOrBuilder() {
        if (snapshotBuilder_ != null) {
          return snapshotBuilder_.getMessageOrBuilder();
        } else {
          return snapshot_;
        }
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Snapshot snapshot = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          mesos.internal.state.State.Operation.Snapshot, mesos.internal.state.State.Operation.Snapshot.Builder, mesos.internal.state.State.Operation.SnapshotOrBuilder> 
          getSnapshotFieldBuilder() {
        if (snapshotBuilder_ == null) {
          snapshotBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              mesos.internal.state.State.Operation.Snapshot, mesos.internal.state.State.Operation.Snapshot.Builder, mesos.internal.state.State.Operation.SnapshotOrBuilder>(
                  snapshot_,
                  getParentForChildren(),
                  isClean());
          snapshot_ = null;
        }
        return snapshotBuilder_;
      }

      // optional .mesos.internal.state.Operation.Expunge expunge = 3;
      private mesos.internal.state.State.Operation.Expunge expunge_ = mesos.internal.state.State.Operation.Expunge.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          mesos.internal.state.State.Operation.Expunge, mesos.internal.state.State.Operation.Expunge.Builder, mesos.internal.state.State.Operation.ExpungeOrBuilder> expungeBuilder_;
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public boolean hasExpunge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public mesos.internal.state.State.Operation.Expunge getExpunge() {
        if (expungeBuilder_ == null) {
          return expunge_;
        } else {
          return expungeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public Builder setExpunge(mesos.internal.state.State.Operation.Expunge value) {
        if (expungeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expunge_ = value;
          onChanged();
        } else {
          expungeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public Builder setExpunge(
          mesos.internal.state.State.Operation.Expunge.Builder builderForValue) {
        if (expungeBuilder_ == null) {
          expunge_ = builderForValue.build();
          onChanged();
        } else {
          expungeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public Builder mergeExpunge(mesos.internal.state.State.Operation.Expunge value) {
        if (expungeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              expunge_ != mesos.internal.state.State.Operation.Expunge.getDefaultInstance()) {
            expunge_ =
              mesos.internal.state.State.Operation.Expunge.newBuilder(expunge_).mergeFrom(value).buildPartial();
          } else {
            expunge_ = value;
          }
          onChanged();
        } else {
          expungeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public Builder clearExpunge() {
        if (expungeBuilder_ == null) {
          expunge_ = mesos.internal.state.State.Operation.Expunge.getDefaultInstance();
          onChanged();
        } else {
          expungeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public mesos.internal.state.State.Operation.Expunge.Builder getExpungeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getExpungeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      public mesos.internal.state.State.Operation.ExpungeOrBuilder getExpungeOrBuilder() {
        if (expungeBuilder_ != null) {
          return expungeBuilder_.getMessageOrBuilder();
        } else {
          return expunge_;
        }
      }
      /**
       * <code>optional .mesos.internal.state.Operation.Expunge expunge = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          mesos.internal.state.State.Operation.Expunge, mesos.internal.state.State.Operation.Expunge.Builder, mesos.internal.state.State.Operation.ExpungeOrBuilder> 
          getExpungeFieldBuilder() {
        if (expungeBuilder_ == null) {
          expungeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              mesos.internal.state.State.Operation.Expunge, mesos.internal.state.State.Operation.Expunge.Builder, mesos.internal.state.State.Operation.ExpungeOrBuilder>(
                  expunge_,
                  getParentForChildren(),
                  isClean());
          expunge_ = null;
        }
        return expungeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mesos.internal.state.Operation)
    }

    static {
      defaultInstance = new Operation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mesos.internal.state.Operation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mesos_internal_state_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mesos_internal_state_Entry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mesos_internal_state_Operation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mesos_internal_state_Operation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mesos_internal_state_Operation_Snapshot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mesos_internal_state_Operation_Snapshot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mesos_internal_state_Operation_Expunge_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mesos_internal_state_Operation_Expunge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013state.proto\022\024mesos.internal.state\"2\n\005E" +
      "ntry\022\014\n\004name\030\001 \002(\t\022\014\n\004uuid\030\002 \002(\014\022\r\n\005valu" +
      "e\030\003 \002(\014\"\251\002\n\tOperation\0222\n\004type\030\001 \002(\0162$.me" +
      "sos.internal.state.Operation.Type\022:\n\010sna" +
      "pshot\030\002 \001(\0132(.mesos.internal.state.Opera" +
      "tion.Snapshot\0228\n\007expunge\030\003 \001(\0132\'.mesos.i" +
      "nternal.state.Operation.Expunge\0326\n\010Snaps" +
      "hot\022*\n\005entry\030\001 \002(\0132\033.mesos.internal.stat" +
      "e.Entry\032\027\n\007Expunge\022\014\n\004name\030\001 \002(\t\"!\n\004Type" +
      "\022\014\n\010SNAPSHOT\020\001\022\013\n\007EXPUNGE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mesos_internal_state_Entry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mesos_internal_state_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mesos_internal_state_Entry_descriptor,
              new java.lang.String[] { "Name", "Uuid", "Value", });
          internal_static_mesos_internal_state_Operation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mesos_internal_state_Operation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mesos_internal_state_Operation_descriptor,
              new java.lang.String[] { "Type", "Snapshot", "Expunge", });
          internal_static_mesos_internal_state_Operation_Snapshot_descriptor =
            internal_static_mesos_internal_state_Operation_descriptor.getNestedTypes().get(0);
          internal_static_mesos_internal_state_Operation_Snapshot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mesos_internal_state_Operation_Snapshot_descriptor,
              new java.lang.String[] { "Entry", });
          internal_static_mesos_internal_state_Operation_Expunge_descriptor =
            internal_static_mesos_internal_state_Operation_descriptor.getNestedTypes().get(1);
          internal_static_mesos_internal_state_Operation_Expunge_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mesos_internal_state_Operation_Expunge_descriptor,
              new java.lang.String[] { "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
