/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.groupon.jesos;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.groupon.jesos.TestProtos.ExtBase.type);
  }
  public interface BaseOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Base> {

    // required .test.Base.Type type = 1;
    /**
     * <code>required .test.Base.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .test.Base.Type type = 1;</code>
     */
    com.groupon.jesos.TestProtos.Base.Type getType();
  }
  /**
   * Protobuf type {@code test.Base}
   */
  public static final class Base extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Base> implements BaseOrBuilder {
    // Use Base.newBuilder() to construct.
    private Base(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.groupon.jesos.TestProtos.Base, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Base(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Base defaultInstance;
    public static Base getDefaultInstance() {
      return defaultInstance;
    }

    public Base getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Base(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.groupon.jesos.TestProtos.Base.Type value = com.groupon.jesos.TestProtos.Base.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.groupon.jesos.TestProtos.internal_static_test_Base_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.groupon.jesos.TestProtos.internal_static_test_Base_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.groupon.jesos.TestProtos.Base.class, com.groupon.jesos.TestProtos.Base.Builder.class);
    }

    public static com.google.protobuf.Parser<Base> PARSER =
        new com.google.protobuf.AbstractParser<Base>() {
      public Base parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Base(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Base> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code test.Base.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EXT_BASE = 1;</code>
       */
      EXT_BASE(0, 1),
      ;

      /**
       * <code>EXT_BASE = 1;</code>
       */
      public static final int EXT_BASE_VALUE = 1;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return EXT_BASE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.groupon.jesos.TestProtos.Base.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:test.Base.Type)
    }

    private int bitField0_;
    // required .test.Base.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.groupon.jesos.TestProtos.Base.Type type_;
    /**
     * <code>required .test.Base.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .test.Base.Type type = 1;</code>
     */
    public com.groupon.jesos.TestProtos.Base.Type getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.groupon.jesos.TestProtos.Base.Type.EXT_BASE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.groupon.jesos.TestProtos.Base>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.groupon.jesos.TestProtos.Base parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.Base parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.groupon.jesos.TestProtos.Base parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.groupon.jesos.TestProtos.Base parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.groupon.jesos.TestProtos.Base prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Base}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.groupon.jesos.TestProtos.Base, Builder> implements com.groupon.jesos.TestProtos.BaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.groupon.jesos.TestProtos.internal_static_test_Base_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.groupon.jesos.TestProtos.internal_static_test_Base_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.groupon.jesos.TestProtos.Base.class, com.groupon.jesos.TestProtos.Base.Builder.class);
      }

      // Construct using com.groupon.jesos.TestProtos.Base.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.groupon.jesos.TestProtos.Base.Type.EXT_BASE;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.groupon.jesos.TestProtos.internal_static_test_Base_descriptor;
      }

      public com.groupon.jesos.TestProtos.Base getDefaultInstanceForType() {
        return com.groupon.jesos.TestProtos.Base.getDefaultInstance();
      }

      public com.groupon.jesos.TestProtos.Base build() {
        com.groupon.jesos.TestProtos.Base result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.groupon.jesos.TestProtos.Base buildPartial() {
        com.groupon.jesos.TestProtos.Base result = new com.groupon.jesos.TestProtos.Base(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.groupon.jesos.TestProtos.Base) {
          return mergeFrom((com.groupon.jesos.TestProtos.Base)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.groupon.jesos.TestProtos.Base other) {
        if (other == com.groupon.jesos.TestProtos.Base.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.groupon.jesos.TestProtos.Base parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.groupon.jesos.TestProtos.Base) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .test.Base.Type type = 1;
      private com.groupon.jesos.TestProtos.Base.Type type_ = com.groupon.jesos.TestProtos.Base.Type.EXT_BASE;
      /**
       * <code>required .test.Base.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .test.Base.Type type = 1;</code>
       */
      public com.groupon.jesos.TestProtos.Base.Type getType() {
        return type_;
      }
      /**
       * <code>required .test.Base.Type type = 1;</code>
       */
      public Builder setType(com.groupon.jesos.TestProtos.Base.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .test.Base.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.groupon.jesos.TestProtos.Base.Type.EXT_BASE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.Base)
    }

    static {
      defaultInstance = new Base(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.Base)
  }

  public interface ExtBaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string a = 1;
    /**
     * <code>optional string a = 1;</code>
     */
    boolean hasA();
    /**
     * <code>optional string a = 1;</code>
     */
    java.lang.String getA();
    /**
     * <code>optional string a = 1;</code>
     */
    com.google.protobuf.ByteString
        getABytes();

    // optional string b = 2;
    /**
     * <code>optional string b = 2;</code>
     */
    boolean hasB();
    /**
     * <code>optional string b = 2;</code>
     */
    java.lang.String getB();
    /**
     * <code>optional string b = 2;</code>
     */
    com.google.protobuf.ByteString
        getBBytes();

    // optional string c = 3;
    /**
     * <code>optional string c = 3;</code>
     */
    boolean hasC();
    /**
     * <code>optional string c = 3;</code>
     */
    java.lang.String getC();
    /**
     * <code>optional string c = 3;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();

    // optional uint32 d = 4;
    /**
     * <code>optional uint32 d = 4;</code>
     */
    boolean hasD();
    /**
     * <code>optional uint32 d = 4;</code>
     */
    int getD();

    // optional string e = 5;
    /**
     * <code>optional string e = 5;</code>
     */
    boolean hasE();
    /**
     * <code>optional string e = 5;</code>
     */
    java.lang.String getE();
    /**
     * <code>optional string e = 5;</code>
     */
    com.google.protobuf.ByteString
        getEBytes();
  }
  /**
   * Protobuf type {@code test.ExtBase}
   */
  public static final class ExtBase extends
      com.google.protobuf.GeneratedMessage
      implements ExtBaseOrBuilder {
    // Use ExtBase.newBuilder() to construct.
    private ExtBase(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExtBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExtBase defaultInstance;
    public static ExtBase getDefaultInstance() {
      return defaultInstance;
    }

    public ExtBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExtBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              a_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              b_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              c_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              d_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              e_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.groupon.jesos.TestProtos.internal_static_test_ExtBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.groupon.jesos.TestProtos.internal_static_test_ExtBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.groupon.jesos.TestProtos.ExtBase.class, com.groupon.jesos.TestProtos.ExtBase.Builder.class);
    }

    public static com.google.protobuf.Parser<ExtBase> PARSER =
        new com.google.protobuf.AbstractParser<ExtBase>() {
      public ExtBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtBase(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExtBase> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string a = 1;
    public static final int A_FIELD_NUMBER = 1;
    private java.lang.Object a_;
    /**
     * <code>optional string a = 1;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string a = 1;</code>
     */
    public java.lang.String getA() {
      java.lang.Object ref = a_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          a_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string a = 1;</code>
     */
    public com.google.protobuf.ByteString
        getABytes() {
      java.lang.Object ref = a_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string b = 2;
    public static final int B_FIELD_NUMBER = 2;
    private java.lang.Object b_;
    /**
     * <code>optional string b = 2;</code>
     */
    public boolean hasB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string b = 2;</code>
     */
    public java.lang.String getB() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          b_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string b = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBBytes() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        b_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c = 3;
    public static final int C_FIELD_NUMBER = 3;
    private java.lang.Object c_;
    /**
     * <code>optional string c = 3;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string c = 3;</code>
     */
    public java.lang.String getC() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 d = 4;
    public static final int D_FIELD_NUMBER = 4;
    private int d_;
    /**
     * <code>optional uint32 d = 4;</code>
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 d = 4;</code>
     */
    public int getD() {
      return d_;
    }

    // optional string e = 5;
    public static final int E_FIELD_NUMBER = 5;
    private java.lang.Object e_;
    /**
     * <code>optional string e = 5;</code>
     */
    public boolean hasE() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string e = 5;</code>
     */
    public java.lang.String getE() {
      java.lang.Object ref = e_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          e_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string e = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEBytes() {
      java.lang.Object ref = e_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        e_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      a_ = "";
      b_ = "";
      c_ = "";
      d_ = 0;
      e_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getABytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, d_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getEBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getABytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, d_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.groupon.jesos.TestProtos.ExtBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.groupon.jesos.TestProtos.ExtBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.ExtBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.groupon.jesos.TestProtos.ExtBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.groupon.jesos.TestProtos.internal_static_test_ExtBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.groupon.jesos.TestProtos.internal_static_test_ExtBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.groupon.jesos.TestProtos.ExtBase.class, com.groupon.jesos.TestProtos.ExtBase.Builder.class);
      }

      // Construct using com.groupon.jesos.TestProtos.ExtBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        a_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        b_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        d_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        e_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.groupon.jesos.TestProtos.internal_static_test_ExtBase_descriptor;
      }

      public com.groupon.jesos.TestProtos.ExtBase getDefaultInstanceForType() {
        return com.groupon.jesos.TestProtos.ExtBase.getDefaultInstance();
      }

      public com.groupon.jesos.TestProtos.ExtBase build() {
        com.groupon.jesos.TestProtos.ExtBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.groupon.jesos.TestProtos.ExtBase buildPartial() {
        com.groupon.jesos.TestProtos.ExtBase result = new com.groupon.jesos.TestProtos.ExtBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.a_ = a_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.b_ = b_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.d_ = d_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.e_ = e_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.groupon.jesos.TestProtos.ExtBase) {
          return mergeFrom((com.groupon.jesos.TestProtos.ExtBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.groupon.jesos.TestProtos.ExtBase other) {
        if (other == com.groupon.jesos.TestProtos.ExtBase.getDefaultInstance()) return this;
        if (other.hasA()) {
          bitField0_ |= 0x00000001;
          a_ = other.a_;
          onChanged();
        }
        if (other.hasB()) {
          bitField0_ |= 0x00000002;
          b_ = other.b_;
          onChanged();
        }
        if (other.hasC()) {
          bitField0_ |= 0x00000004;
          c_ = other.c_;
          onChanged();
        }
        if (other.hasD()) {
          setD(other.getD());
        }
        if (other.hasE()) {
          bitField0_ |= 0x00000010;
          e_ = other.e_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.groupon.jesos.TestProtos.ExtBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.groupon.jesos.TestProtos.ExtBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string a = 1;
      private java.lang.Object a_ = "";
      /**
       * <code>optional string a = 1;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string a = 1;</code>
       */
      public java.lang.String getA() {
        java.lang.Object ref = a_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          a_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a = 1;</code>
       */
      public com.google.protobuf.ByteString
          getABytes() {
        java.lang.Object ref = a_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a = 1;</code>
       */
      public Builder setA(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a = 1;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = getDefaultInstance().getA();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a = 1;</code>
       */
      public Builder setABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }

      // optional string b = 2;
      private java.lang.Object b_ = "";
      /**
       * <code>optional string b = 2;</code>
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string b = 2;</code>
       */
      public java.lang.String getB() {
        java.lang.Object ref = b_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          b_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string b = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBBytes() {
        java.lang.Object ref = b_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          b_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string b = 2;</code>
       */
      public Builder setB(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string b = 2;</code>
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = getDefaultInstance().getB();
        onChanged();
        return this;
      }
      /**
       * <code>optional string b = 2;</code>
       */
      public Builder setBBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        b_ = value;
        onChanged();
        return this;
      }

      // optional string c = 3;
      private java.lang.Object c_ = "";
      /**
       * <code>optional string c = 3;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public java.lang.String getC() {
        java.lang.Object ref = c_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        java.lang.Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder setC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000004);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c = 3;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }

      // optional uint32 d = 4;
      private int d_ ;
      /**
       * <code>optional uint32 d = 4;</code>
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 d = 4;</code>
       */
      public int getD() {
        return d_;
      }
      /**
       * <code>optional uint32 d = 4;</code>
       */
      public Builder setD(int value) {
        bitField0_ |= 0x00000008;
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 d = 4;</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000008);
        d_ = 0;
        onChanged();
        return this;
      }

      // optional string e = 5;
      private java.lang.Object e_ = "";
      /**
       * <code>optional string e = 5;</code>
       */
      public boolean hasE() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string e = 5;</code>
       */
      public java.lang.String getE() {
        java.lang.Object ref = e_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          e_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string e = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEBytes() {
        java.lang.Object ref = e_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          e_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string e = 5;</code>
       */
      public Builder setE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        e_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string e = 5;</code>
       */
      public Builder clearE() {
        bitField0_ = (bitField0_ & ~0x00000010);
        e_ = getDefaultInstance().getE();
        onChanged();
        return this;
      }
      /**
       * <code>optional string e = 5;</code>
       */
      public Builder setEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        e_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.ExtBase)
    }

    static {
      defaultInstance = new ExtBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.ExtBase)
    public static final int TYPE_FIELD_NUMBER = 100;
    /**
     * <code>extend .test.Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.groupon.jesos.TestProtos.Base,
        com.groupon.jesos.TestProtos.ExtBase> type = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.groupon.jesos.TestProtos.ExtBase.getDefaultInstance(),
          0,
          com.groupon.jesos.TestProtos.ExtBase.class,
          com.groupon.jesos.TestProtos.ExtBase.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Base_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Base_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_ExtBase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_ExtBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\004test\"E\n\004Base\022\035\n\004type\030\001 \002(\016" +
      "2\017.test.Base.Type\"\024\n\004Type\022\014\n\010EXT_BASE\020\001*" +
      "\010\010d\020\200\200\200\200\002\"i\n\007ExtBase\022\t\n\001a\030\001 \001(\t\022\t\n\001b\030\002 \001" +
      "(\t\022\t\n\001c\030\003 \001(\t\022\t\n\001d\030\004 \001(\r\022\t\n\001e\030\005 \001(\t2\'\n\004t" +
      "ype\022\n.test.Base\030d \002(\0132\r.test.ExtBaseB\037\n\021" +
      "com.groupon.jesosB\nTestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_test_Base_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_test_Base_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_Base_descriptor,
              new java.lang.String[] { "Type", });
          internal_static_test_ExtBase_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_test_ExtBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_ExtBase_descriptor,
              new java.lang.String[] { "A", "B", "C", "D", "E", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
